### ISSUE TITLE
Bumping versions of AbstractTrees.jl

### ISSUE THREAD

**Issue by mipals** [WaveProp/IFGF.jl#31]
Hi again,

I am having trouble utilizing this package due its restriction to AbstractTrees.jl 0.3 which conflicts with TransformsBase.jl (it only supports 0.4).

Cheers,
Mikkel

**Comment by maltezfaria** [comment]
Are you on `main` or a tagged branch? I will patch this right now.

**Comment by mipals** [comment]
Pretty sure that I was trying on the `main` branch. Anyhow, I also tried with with
```julia
add https://github.com/WaveProp/IFGF.jl.git#main
```
which gives me the same error.

**Comment by mipals** [comment]
Works now. Thanks 👍

**Comment by maltezfaria** [comment]
Thanks. I just pushed the required modifications in https://github.com/WaveProp/IFGF.jl/commit/009b67987b083b926d4998bd25d9d75198206a3b

Both main and `v0.1.1` should be compatible with `v0.4` of `AbstractTrees`. Can you confirm that it works on your side?
